# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: edcaraujo
subtitle: Eduardo Cruz Araujo
epigraphy: The meaning of life is to give life meaning
description: Olá! Seja bem-vindo à minha página. Meu nome é Eduardo e sou apaixonado por tecnologia e inovação. Aqui, você encontrará informações sobre meus projetos, interesses e reflexões sobre o mundo digital.

email: me@edcaraujo.com

url: http://edcaraujo.com

github: edcaraujo
linkedin: edcaraujo
instagram: edcaraujo

# Build settings
markdown: kramdown

# Theme settings
navigation: 
  - index.md
  - presentations/presentations.md
  - publications/publications.md
  - projects/projects.md
  - teaching/teaching.md
  - blog/blog.md

# Plugins settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll_version_plugin